"""
SovereignWorkbench — Shared Interface Contract (app/schemas.py)

CRITICAL: This file is the frozen contract between:
- Rajat (Dev 1: Agentic Brain & LangGraph State Machine)
- Anand (Dev 2: Deterministic Muscle, Sandbox, Compilers & Security)
- Kaushal (Dev 3: GPU Server, Ollama Daemon & Model Gateway)
All developers import from this file. DO NOT modify field names or types without explicit consensus.
"""

from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List
from pathlib import Path


# =====================================================================
# 1. SANDBOX SCHEMAS (Anand implements -> Rajat consumes)
# =====================================================================

class SandboxExecutionRequest(BaseModel):
    """Input payload to execute code in the isolated sandbox."""
    code: str = Field(..., description="The raw Python script generated by the LLM.")
    timeout_seconds: int = Field(default=5, description="Execution timeout cap.")
    memory_limit_mb: int = Field(default=256, description="RAM limit for the sandbox process.")


class SandboxResult(BaseModel):
    """Output returned by the sandbox execution runner."""
    success: bool = Field(..., description="True if script exited with code 0.")
    exit_code: int = Field(..., description="Process exit code (0 = success, non-zero = failure).")
    stdout: str = Field(default="", description="Captured standard output.")
    stderr: str = Field(default="", description="Captured raw standard error.")
    distilled_error: Optional[str] = Field(
        default=None,
        description="Clean 2-line root cause summary parsed from stderr, used for LLM self-healing."
    )
    parsed_output: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Structured JSON/dict parsed from stdout (e.g. remaining_life, corrosion_rate)."
    )


# =====================================================================
# 2. DELIVERABLE COMPILER SCHEMAS (Dev 1 provides -> Dev 2 implements)
# =====================================================================

class PipeInspectionData(BaseModel):
    """Extracted & calculated inspection metrics for a refinery piping line."""
    line_tag: str = Field(..., json_schema_extra={"example": "CDU-2-04-150-A1A"})
    service_description: str = Field(default="Crude Distillation Overhead Vapour")
    material_spec: str = Field(default="ASTM A106 Grade B Carbon Steel")
    design_pressure_psi: float = Field(default=150.0)
    design_temp_celsius: float = Field(default=135.0)
    nominal_thickness_mm: float = Field(..., json_schema_extra={"example": 4.8})
    actual_thickness_mm: float = Field(..., json_schema_extra={"example": 3.2})
    minimum_required_thickness_mm: float = Field(default=2.1)
    corrosion_rate_mm_year: float = Field(default=0.35)
    remaining_life_years: float = Field(..., json_schema_extra={"example": 3.1})
    mandatory_action: str = Field(..., json_schema_extra={"example": "SCHEDULE SHUTDOWN REPLACEMENT (< 5 YRS)"})
    inspection_date: str = Field(default="September 2026")
    inspector_name: str = Field(default="Chief Plant Inspector, MRPL")


class CostEstimateItem(BaseModel):
    """Individual line item for the financial cost matrix."""
    item_code: str
    description: str
    quantity: float
    unit: str
    unit_rate_inr: float
    total_inr: float


class ApprovalNotePayload(BaseModel):
    """Complete payload required to compile the executive Word Approval Note."""
    reference_number: str = Field(default="MRPL/CDU-2/MAINT/2026/089")
    unit_name: str = Field(default="Crude Distillation Unit 2 (CDU-2)")
    inspection_data: PipeInspectionData
    formula_derivation_steps: List[str] = Field(
        default=[
            "Corrosion Rate = (t_nominal - t_actual) / operating_years = (4.8 - 3.2) / 4.5 = 0.35 mm/yr",
            "t_minimum = (P * D) / (2 * S * E + 2 * Y * P) = 2.1 mm (per ASME B31.3)",
            "Remaining Life = (t_actual - t_minimum) / corrosion_rate = (3.2 - 2.1) / 0.35 = 3.14 years",
            "Statutory Mandate: API 570 Section 7.1 requires replacement when remaining life < 5 years."
        ]
    )
    recommended_action: str = Field(
        default="Procure 150-meter spool ASTM A106-B pipe and schedule replacement during Q4 turnaround."
    )
    signatory_title: str = Field(default="Superintendent Engineer (Process Maintenance), MRPL")


class CostMatrixPayload(BaseModel):
    """Payload required to compile the Excel Cost & Risk Workbook."""
    project_title: str = Field(default="MRPL CDU-2 Line Replacement & Procurement Estimate")
    line_tag: str = Field(default="CDU-2-04-150-A1A")
    items: List[CostEstimateItem] = Field(
        default=[
            CostEstimateItem(item_code="PIPE-01", description="Seamless Pipe ASTM A106-B 6-inch", quantity=150.0, unit="Meters", unit_rate_inr=4500.0, total_inr=675000.0),
            CostEstimateItem(item_code="FLG-02", description="Weld Neck Flange Class 150 RF", quantity=12.0, unit="Nos", unit_rate_inr=6200.0, total_inr=74400.0),
            CostEstimateItem(item_code="FAB-03", description="Prefabrication & Spool Welding", quantity=1.0, unit="Lump Sum", unit_rate_inr=180000.0, total_inr=180000.0),
            CostEstimateItem(item_code="NDT-04", description="Post-Weld Radiographic Testing (RT)", quantity=18.0, unit="Joints", unit_rate_inr=2500.0, total_inr=45000.0),
            CostEstimateItem(item_code="INS-05", description="Thermal Insulation & Cladding", quantity=150.0, unit="Meters", unit_rate_inr=1200.0, total_inr=180000.0)
        ]
    )
    contingency_percentage: float = Field(default=10.0)
    remaining_life_years: Optional[float] = Field(
        default=None,
        description="Calculated remaining service life in years per API 570."
    )


# =====================================================================
# 3. RAG SCHEMAS (Dev 2 implements -> Dev 1 consumes)
# =====================================================================

class RagChunk(BaseModel):
    """A retrieved context chunk from refinery SOPs or standards."""
    doc_name: str = Field(..., json_schema_extra={"example": "OISD-STD-118.pdf"})
    clause_reference: str = Field(..., json_schema_extra={"example": "Section 4.2: In-service Inspection Frequency"})
    text_content: str = Field(...)
    relevance_score: float = Field(..., json_schema_extra={"example": 0.89})


class RagQueryResponse(BaseModel):
    """Result of searching the local Sovereign RAG vector store."""
    query: str
    chunks: List[RagChunk]
    combined_context: str


# =====================================================================
# 4. SECURITY & TELEMETRY SCHEMAS (Dev 2 implements -> Dev 1 & UI consume)
# =====================================================================

class NetworkStats(BaseModel):
    """Real-time network socket telemetry proving zero outbound WAN bytes."""
    timestamp: str
    wan_interface: str = Field(default="eth0/wlan0")
    total_rx_bytes: int
    total_tx_bytes: int
    outbound_wan_bytes_delta: int = Field(
        default=0,
        description="Must be exactly 0 during demo to prove air-gap compliance."
    )
    air_gap_status: str = Field(default="LOCKED_AIR_GAP_COMPLIANT")
    is_air_gapped: bool = Field(
        default=True,
        description="True if completely air-gapped without external WAN leak, False otherwise."
    )
    external_gateway_detected: bool = Field(
        default=False,
        description="True if a default gateway or WAN route is detected."
    )
    active_local_connections: int = Field(
        default=1,
        description="Active local network socket connections (LAN/localhost)."
    )


class AuditEvent(BaseModel):
    """A single append-only cryptographic transaction for the audit chain."""
    event_id: Optional[str] = None
    timestamp: Optional[str] = None
    user_role: str = Field(..., json_schema_extra={"example": "senior_engineer"})
    model_id: str = Field(..., json_schema_extra={"example": "deepseek-r1:8b"})
    task_type: str = Field(..., json_schema_extra={"example": "api_570_calculation"})
    prompt_hash: str = Field(..., description="SHA-256 hash of input prompt/data.")
    tool_exit_code: int = Field(default=0)
    output_hash: str = Field(..., description="SHA-256 hash of output result.")
    previous_hash: Optional[str] = Field(default=None, description="SHA-256 hash of previous audit log row.")
    entry_hash: Optional[str] = Field(default=None, description="SHA-256 hash of this complete row.")
