#!/usr/bin/env bash
# =====================================================================
# SovereignWorkbench — Static LAN Netplan Setup (scripts/setup_lan_nodes.sh)
# Configures Ubuntu Netplan for 3-Node Physical Offline LAN Architecture
# Enforces zero-gateway air-gap isolation at the Linux kernel level.
# =====================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}=====================================================================${NC}"
echo -e "${BLUE}🛡️  SOVEREIGNWORKBENCH — PHYSICAL AIR-GAP NETPLAN CONFIGURATOR      ${NC}"
echo -e "${BLUE}=====================================================================${NC}"

if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}❌ Please run with sudo: sudo ./scripts/setup_lan_nodes.sh${NC}"
  exit 1
fi

echo -e "\nSelect the Physical Node to configure for this machine:"
echo -e "  1) ${GREEN}Node 1: SERVER NODE${NC}       (Static IP: 192.168.1.100/24)"
echo -e "  2) ${GREEN}Node 2: ADMIN / AUDIT NODE${NC} (Static IP: 192.168.1.101/24)"
echo -e "  3) ${GREEN}Node 3: USER WORKBENCH${NC}    (Static IP: 192.168.1.102/24)"
echo -e "  q) Quit"

read -p "Enter choice [1-3]: " CHOICE

case "$CHOICE" in
  1)
    NODE_NAME="Server Node"
    NODE_IP="192.168.1.100"
    ;;
  2)
    NODE_NAME="Admin / Audit Node"
    NODE_IP="192.168.1.101"
    ;;
  3)
    NODE_NAME="User Workbench Client"
    NODE_IP="192.168.1.102"
    ;;
  *)
    echo "Exiting without changes."
    exit 0
    ;;
esac

# Detect primary ethernet interface (e.g., eth0, enp3s0)
IFACE=$(ip -o link show | awk -F': ' '$2 ~ /^(eth|en|enp|eno)/ {print $2; exit}')
if [ -z "$IFACE" ]; then
  echo -e "${YELLOW}⚠️  No standard ethernet interface detected. Defaulting to 'eth0'.${NC}"
  IFACE="eth0"
else
  echo -e "Detected primary network interface: ${GREEN}${IFACE}${NC}"
fi

NETPLAN_FILE="/etc/netplan/01-sih-lan.yaml"

echo -e "\nWriting Netplan configuration to ${NETPLAN_FILE}..."

cat <<EOF > "$NETPLAN_FILE"
# MRPL SovereignWorkbench 3-Node Physical Offline LAN
# Generated by SovereignWorkbench setup script
network:
  version: 2
  renderer: networkd
  ethernets:
    ${IFACE}:
      addresses:
        - ${NODE_IP}/24
      routes: []           # NO default gateway = strictly offline OS kernel
      nameservers:
        addresses: []     # NO external DNS resolution configured
EOF

chmod 600 "$NETPLAN_FILE"

echo -e "${GREEN}✅ Netplan configuration written successfully.${NC}"
echo -e "Applying configuration with: ${YELLOW}netplan apply${NC}..."

netplan apply

echo -e "\n${BLUE}--- Verification ---${NC}"
echo -e "Configured Node: ${GREEN}${NODE_NAME}${NC}"
echo -e "IP Address:      ${GREEN}${NODE_IP}/24${NC}"
echo -e "Default Gateway: ${RED}NONE (Strictly Air-Gapped)${NC}"
echo -e "External DNS:    ${RED}DISABLED${NC}"
echo -e "\nRouting table check:"
ip route show

echo -e "\n${GREEN}🎉 ${NODE_NAME} network configuration complete!${NC}"
